### ISSUE TITLE
[WEB] Skia renderer makes fonts thinner than HTML renderer.

### ISSUE THREAD

**Issue by solid-dimakoniaiev** [solid-dimakoniaiev/test_buildkite#2]
## Steps to Reproduce
1. Run `flutter create sample`.
2. Update the files as follows:
main.dart :
```import ‘package:flutter/material.dart’;
void main() {
  runApp(MyApp());
}
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: ‘Flutter Demo’,
      theme: ThemeData(primarySwatch: Colors.blue),
      home: MyHomePage(),
    );
  }
}
class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: Text(
          ‘Lorem ipsum dolor sit amet, ’
          ‘consectetur adipiscing elit, ’
          ‘sed do eiusmod tempor’,
          style: TextStyle(fontFamily: ‘Roboto’,),
        ),
      ),
    );
  }
}
```
pubspec.yaml:
```
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Black.ttf
          weight: 900
```
Download the following [Roboto font](https://fonts.google.com/download?family=Roboto) and add the content to the top-level `fonts` folder.
3. Use `flutter run -d chrome --release`  and `flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true` to run with the different renderers.
**Expected results:** No differences in fonts rendering.
**Actual results:** Skia renderer makes fonts thinner than HTML renderer.
The first line - screenshot from [Google Fonts](https://fonts.google.com/specimen/Roboto?preview.text=Lorem%20ipsum%20dolor%20sit%20amet,%20consectetur%20adipiscing%20elit,%20sed%20do%20eiusmod%20tempor&preview.text_type=custom).
The second one - using default HTML renderer.
The third line - using Skia renderer.
![fonts](https://user-images.githubusercontent.com/68225012/99074581-ac52fb00-25c0-11eb-9f49-a31092e7a093.png)
<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.231, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-UA)
    • Flutter version 1.24.0-8.0.pre.231 at /Users/user/Desktop/development/flutter
    • Framework revision ed977dd6a4 (22 minutes ago), 2020-11-13 09:01:09 -0800
    • Engine revision dddb532b5c
    • Dart version 2.12.0 (build 2.12.0-37.0.dev)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      :hammer: https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070
[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.193
• No issues found!
```
</details>
